apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: git-init
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-git-clone/git-init@sha256:22b45d5ca99f59af4b2050d8d2630b39fb76848e74f1bbf445de17a9b8339556
        name: my-go
        resources: {}
status: {}
