apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: git-init
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/tekton-ecosystem-tenant/tektoncd-git-clone/git-init@sha256:80b9b2f9160334f28ea91c08a7c83aa509ba511e942e78e9b8f2288796df5b8f
        name: my-go
        resources: {}
status: {}
