apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: git-init
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: git-init
    app.kubernetes.io/part-of: tektoncd-git-clone
  name: git-inityyig
spec:
  path: /
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: git-init
    weight: null
status: {}
